# Generated by Django 3.1.1 on 2020-09-26 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='movies',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.movies'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='characters',
        ),
        migrations.AddField(
            model_name='user',
            name='characters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.character'),
            preserve_default=False,
        ),
    ]
