# Generated by Django 3.1.1 on 2020-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200926_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('characters', models.ManyToManyField(to='quickstart.Character1')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='characters',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movies1',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='character1',
            name='movies',
            field=models.ManyToManyField(to='quickstart.Movies1'),
        ),
    ]
