# Generated by Django 3.1.1 on 2020-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200926_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.character')),
            ],
        ),
        migrations.RemoveField(
            model_name='user1',
            name='characters',
        ),
        migrations.DeleteModel(
            name='Character1',
        ),
        migrations.DeleteModel(
            name='Movies1',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.movies'),
        ),
    ]
