# Generated by Django 3.1.1 on 2020-09-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20200926_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.movies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.character'),
        ),
    ]
