# Generated by Django 3.1.1 on 2020-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200926_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='movies',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='quickstart.Movies'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='characters',
        ),
        migrations.AddField(
            model_name='user',
            name='characters',
            field=models.ManyToManyField(to='quickstart.Character'),
        ),
    ]
